# Generated by Django 3.2.8 on 2021-11-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_name_todo_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='name',
        ),
    ]
