# Generated by Django 3.2.8 on 2021-11-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_task_todo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='1990-08-21'),
            preserve_default=False,
        ),
    ]
